version: 2.1

orbs:
  node: circleci/node@5.0.1

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
        pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm test

   publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: tofucodes/cimg/node:16.10
      - docker/push:
          image: tofucodes/cimg/node:16.10
  
  # Assignmentdoc

# workflow names need to match above
# requires in this case means that build needs to happen before test
workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:            
            - test


