version: 2.1

orbs:
  node: circleci/node@5.0.1

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
        pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm test

  
  publish:
    docker:
        - image: cimg/node:16.10
    steps:
        - checkout
        #Log into dockerhub
        - run: 
            docker build -t tofucodes/cimg/node:16.10 .
        - run: 
            docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        - run: 
            docker push tofucodes/cimg/node:16.10
  deploy:
    docker:
      - image: cimg/node:16.10
      steps:
      - setup_remote_docker      
      - heroku/install
      - checkout
      - run:
          name: Heroku Container Push
          command: | 
              heroku container:login
              heroku container:push web -a tofucodes
              heroku container:release web -a tofucodes

  # Assignmentdoc

# workflow names need to match above
# requires in this case means that build needs to happen before test
# Assignment 4.6
workflows:
  simple_workflow:
    jobs:
      - build
        filters:
          branches:
            only:
              - main
              - release
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - main
                - release
      - publish:
          requires:            
            - test
          filters:
            branches:
              only:
                - release
      - deploy:
        requires:
          - publish
        filters:
            branches:
              only:
                - release


